HOSTS:
  archlinux-current-x64:
    platform: archlinux-current-amd64
    hypervisor: docker
    image: archimg/base-devel:latest
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'echo "en_US.UTF-8 UTF-8" > /etc/locale.gen'
CONFIG:
  trace_limit: 200
