fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    sudo:
      repo: "https://github.com/saz/puppet-sudo.git"
      ref: "v3.1.0"
    ssh: "https://github.com/saz/puppet-ssh.git"
    firewall: "https://github.com/puppetlabs/puppetlabs-firewall.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
    staging: "https://github.com/nanliu/puppet-staging.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    docker: "https://github.com/garethr/garethr-docker.git"
  symlinks:
    archlinux_workstation: "#{source_dir}"
