fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.12.0"
    sudo:
      repo: "https://github.com/saz/puppet-sudo.git"
      ref: "v4.2.0"
    ssh: "https://github.com/saz/puppet-ssh.git"
    firewall: "https://github.com/puppetlabs/puppetlabs-firewall.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
    staging: "https://github.com/nanliu/puppet-staging.git"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "2.2.1"
    docker: "https://github.com/garethr/garethr-docker.git"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "2.3.0"
    epel:
      repo: "https://github.com/stahnma/puppet-module-epel.git"
      ref: "1.3.0"
  symlinks:
    archlinux_workstation: "#{source_dir}"
